COUNTRY_MAP = {
    "United Kingdom": "UK",
    "France": "FR",
    "Australia": "AU",
    "Netherlands": "NL",
    "Germany": "DE",
    "Norway": "NO",
    "EIRE": "IE",
    "Switzerland": "CH",
    "Spain": "ES",
    "Poland": "PL",
    "Portugal": "PT",
    "Italy": "IT",
    "Belgium": "BE",
    "Lithuania": "LT",
    "Japan": "JP",
    "Iceland": "IS",
    "Channel Islands": "CI",
    "Denmark": "DK",
    "Cyprus": "CY",
    "Sweden": "SE",
    "Austria": "AT",
    "Israel": "IL",
    "Finland": "FI",
    "Bahrain": "BH",
    "Greece": "GR",
    "Hong Kong": "HK",
    "Singapore": "SG",
    "Lebanon": "LB",
    "United Arab Emirates": "AE",
    "Saudi Arabia": "SA",
    "Czech Republic": "CZ",
    "Canada": "CA",
    "Unspecified": "UNS",
    "Brazil": "BR",
    "USA": "US",
    "European Community": "EC",
    "Malta": "MT",
    "RSA": "ZA",
}
